### ISSUE TITLE
Understand XML config

### ISSUE THREAD

**Issue by lbaltaru** [cross-logis/cross-config#1]
Create a new XML configuration for some dummy objects (nodes and links).

Alex will document in an example file (similar to PNI probe configuration).

Each team member will generate a new XML file and will import the configuration in CROSS (local env).

**Comment by lbaltaru** [comment]
> A wiki page has been created at https://github.com/cross-logis/cross-config/wiki/CROSS-XML-Configuration-Documentation that contains a small documentation for most object types from a demo configuration.

@alexctinpirtea 
Technology definition is missing?!

**Comment by alexctinpirtea** [comment]
> > A wiki page has been created at https://github.com/cross-logis/cross-config/wiki/CROSS-XML-Configuration-Documentation that contains a small documentation for most object types from a demo configuration.
> 
> @alexctinpirtea
> Technology definition is missing?!

Technology trees and technologies definitions have been added to the wiki as follows:

- [technologytrees](https://github.com/cross-logis/cross-config/wiki/CROSS-XML-Configuration-Documentation#technologytrees)

- [technologies](https://github.com/cross-logis/cross-config/wiki/CROSS-XML-Configuration-Documentation#technologies)
