### ISSUE TITLE
Create an example of XML configuration

### ISSUE THREAD

**Issue by alexctinpirtea** [cross-logis/cross-config#2]
TBD by @lbaltaru

**Comment by lbaltaru** [comment]
- create a node type: Tower (not root)
  - Tower can be inserted under Locality
  - Add custom attribute Height to the Tower (use existing CA)
- Create a new link type: Radio Link
  - can be terminated on:
    - Tower (q=5)
    - Radio IDU (q=1)
    - Network Element  (q=2)
  - routing consistency
    - Tower, Radio IDU, Network Element
  - allow consumer link types
    - STM1 (channel); channels = 0
    - Ethernet 100M (channel); channels = 0
    - Ethernet 1G (channel); channels = 0
  - providers
    - Radio Frequency Link (serial)
    - Wave Guide (serial)
  - custom attribute: Radio Channels (logic - count the number of radio channels used)


To be continued...

**Comment by alexctinpirtea** [comment]
Example 1 and Example 2 xml files have been pushed to the repository, commit 3be0fc280342f4fb48ad8f29dbdc1a9d1dc82b36.
Groovy code for Example 1 will be added soon.
